const axios = require('axios');
const httpStatus = require('http-status');
const ApiError = require('../utils/ApiError');

const GITHUB_API = 'https://api.github.com';
const TARGET_OWNER = 'slingbiz';
const TARGET_REPO = 'sling-fe';

// The sandbox (sling-studio) executes widget code via scope injection: bare
// identifiers resolved as Function() parameters, no import statements
// (codePolicy.js there rejects imports outright, since the sandbox can't run
// them). A real file in sling-fe needs actual imports, so this list detects
// which React hooks the code references and only imports those. False
// positives (importing an unused hook) are harmless; missing one isn't.
const REACT_HOOKS = ['useState', 'useEffect', 'useCallback', 'useMemo', 'useRef', 'useContext'];

function githubHeaders() {
  const token = process.env.GITHUB_PUBLISH_TOKEN;
  if (!token) {
    throw new ApiError(httpStatus.INTERNAL_SERVER_ERROR, 'GITHUB_PUBLISH_TOKEN is not configured');
  }
  return {
    Authorization: `Bearer ${token}`,
    Accept: 'application/vnd.github+json',
    'X-GitHub-Api-Version': '2022-11-28',
  };
}

// Returns the file's current sha (needed to update it), or null if it
// doesn't exist yet (so it should be created instead).
async function getFileSha(path) {
  try {
    const res = await axios.get(
      `${GITHUB_API}/repos/${TARGET_OWNER}/${TARGET_REPO}/contents/${path}`,
      {headers: githubHeaders()},
    );
    return res.data.sha;
  } catch (err) {
    if (err.response && err.response.status === 404) return null;
    throw err;
  }
}

async function putFile(path, content, message) {
  const sha = await getFileSha(path);
  const body = {
    message,
    content: Buffer.from(content, 'utf8').toString('base64'),
  };
  if (sha) body.sha = sha;

  const res = await axios.put(
    `${GITHUB_API}/repos/${TARGET_OWNER}/${TARGET_REPO}/contents/${path}`,
    body,
    {headers: githubHeaders()},
  );
  return res.data;
}

function buildComponentFile(widget) {
  const code = (widget.code || '').trim();
  const usedHooks = REACT_HOOKS.filter((hook) => new RegExp(`\\b${hook}\\b`).test(code));
  const reactImport = usedHooks.length
    ? `import React, {${usedHooks.join(', ')}} from 'react';`
    : `import React from 'react';`;

  const dependencyImports = Object.entries(widget.dependencies || {})
    .filter(([, names]) => Array.isArray(names) && names.length > 0)
    .map(([lib, names]) => `import {${names.join(', ')}} from '${lib}';`);

  return [reactImport, ...dependencyImports, '', code, '', 'export default PreviewComponent;', ''].join('\n');
}

function buildWidgetJson(widget) {
  return `${JSON.stringify(
    {
      version: 1,
      name: widget.name,
      key: widget.key,
      description: widget.description,
      type: widget.type,
      ownership: widget.ownership,
      icon: widget.icon,
      props: widget.props || [],
      source: 'ai_generated',
    },
    null,
    2,
  )}\n`;
}

// Fully rewritten on every publish rather than appended-to: regenerating the
// whole file from the current list of published AI widgets is simpler and
// safer than trying to patch a hand-rolled diff into it, and this file is
// never hand-edited so there's nothing to lose by overwriting it.
function buildGeneratedRegistryFile(publishedWidgets) {
  const header = [
    '// AUTO-GENERATED by sling-api\'s widget publish flow.',
    '// Do not hand-edit — this file is fully rewritten on every AI widget publish.',
    "import dynamic from 'next/dynamic';",
    "import {registerWidget} from 'sling-core';",
    '',
  ].join('\n');

  const entries = publishedWidgets
    .map((w) =>
      [
        'registerWidget(',
        `  ${JSON.stringify(w.name)},`,
        `  dynamic(() => import('./${w.key}'), {ssr: false}),`,
        '  {',
        `    description: ${JSON.stringify(w.description)},`,
        `    ownership: ${JSON.stringify(w.ownership)},`,
        `    type: ${JSON.stringify(w.type)},`,
        `    key: ${JSON.stringify(w.key)},`,
        `    icon: ${JSON.stringify(w.icon)},`,
        `    props: ${JSON.stringify(w.props || [])},`,
        '  },',
        ');',
      ].join('\n'),
    )
    .join('\n\n');

  return `${header}\n${entries}\n`;
}

/**
 * Writes an approved AI-generated widget into sling-fe as real files:
 * the component itself, its metadata sidecar, and a rebuilt registry
 * listing every currently-published AI widget. Three separate commits
 * (one per file) rather than a single tree commit, trading a small amount
 * of git noise for much simpler code — each is just a Contents API PUT.
 */
async function publishGeneratedWidgetToRepo(widget, allPublishedAiWidgets) {
  const componentPath = `widgets/generated/${widget.key}/index.js`;
  const widgetJsonPath = `widgets/generated/${widget.key}/widget.json`;
  const registryPath = 'widgets/generated/index.js';

  await putFile(componentPath, buildComponentFile(widget), `Publish AI-generated widget: ${widget.key}`);
  await putFile(widgetJsonPath, buildWidgetJson(widget), `Publish AI-generated widget metadata: ${widget.key}`);
  await putFile(
    registryPath,
    buildGeneratedRegistryFile(allPublishedAiWidgets),
    `Update generated widget registry (publishing ${widget.key})`,
  );
}

module.exports = {
  buildComponentFile,
  buildWidgetJson,
  buildGeneratedRegistryFile,
  publishGeneratedWidgetToRepo,
  getFileSha,
  putFile,
};
