module.exports = {
  GLOBAL_SLING_HANDLER: ['/[[...global]]', '/[...global]'],
  CLIENT_VERIFICATION_STEPS: {
    COMPANY_REGISTERED: 'COMPANY_REGISTERED',
    MEMBERSHIP_SELECTED: 'MEMBERSHIP_SELECTED',
    COMPLETED: 'COMPLETED',
  },
};
